### ISSUE TITLE
breakfast_frame_bin3.json

### ISSUE THREAD

**Issue by doveomgggggg** [pangzhan27/GTLA#1]
Hi，
In this code，you have mentioned that you used the breakfast_frame_bin3.json，but I didn't see this file in the code.
Could you share this json file or the structure of the json file?
Thank you.

**Comment by pangzhan27** [comment]
Thank you for your interest in our work. 
I have uploaded the missing file to the data folder.

**Comment by doveomgggggg** [comment]
> Thank you for your interest in our work. I have uploaded the missing file to the data folder.

Thank you very much for your sharing
